version: "3.8"
services:
  frontend:
    stdin_open: true # put you inside the container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - "app/node_modules" # in case you need to debug some node_modules
      - "./:/app" # HOT Reload enabled
    command: yarn run start
